### ISSUE TITLE
Integrate door busser

### ISSUE THREAD

**Issue by ML19821** [andrasU/openhab-addons#11]
I've a feature request. Please integrate the door busser from the free@homeTouch7.

Currently the touch panel is detected by the binding, but I have a HANDLER_INITIALIZING_ERROR.
<img width="574" alt="image" src="https://user-images.githubusercontent.com/96960914/215272591-f60129de-93b5-4d23-8ccd-000889ec50eb.png">

Maybe the screenshots from the kjoglums-binding will help:
![image](https://user-images.githubusercontent.com/96960914/215272639-bde02530-7f6d-4a69-a5a2-d2a200919700.png)
![image](https://user-images.githubusercontent.com/96960914/215272645-e44afe6b-dd4f-489b-bd02-0db6ca6f00cc.png)

**Comment by andrasU** [comment]
@ML19821: I fixed the buzzer in the last binding version. if it is not working, please send me the swagger JSON esport of the device.
In my binding the configuration is done via functionID and pairingID, based on this information the binding is searching automatically the IDP and ODP values.

**Comment by ML19821** [comment]
i've still the  HANDLER_INITIALIZING_ERROR.
Here some Information from Taillog:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/96960914/216766222-3ee223f0-530b-4115-a44f-e040ff7f2a7b.png">
<img width="1880" alt="image" src="https://user-images.githubusercontent.com/96960914/216766243-a8245bd4-52b6-403e-8b50-07897bb07d07.png">

And here the JSON from swagger
[response_1675511561088.json.txt](https://github.com/andrasU/openhab-addons/files/10608543/response_1675511561088.json.txt)

**Comment by andrasU** [comment]
@ML19821 I think I found the root cause of the issues...

The root cause was not the door opener itself, but strange channels surrounding the door opener. E.g. channel 2 is not having any function ID, which led to a wrong channel detection code (it wrongly recognised as SENSOR device). Because my binding is not need any configuration for devices or the channels, but the JSON output from the SysAP is parsed and all channels are added to the thing which is known by the binding. below is the "strange"part of the JSON output.

               "ch0002":{
                  "displayName":"1,1,3",
                  "functionID":"",
                  "inputs":{
                     
                  },
                  "outputs":{
                     
                  }
               },

This use-case was unfortunately not handled in the binding but now, I corrected the code, make safeguarding for the "empty" function ids. Tested on my test environment with your JSON output and it worked.

I could not test the door opener is working, but at least the detection is OK.

If you have a bit time it would be great if you could test the function also.

The release is here [fh-3.4.4](https://github.com/andrasU/openhab-addons/releases/tag/fh-3.4.4)

Thank you

**Comment by ML19821** [comment]
successfully tested with the thing "Default Door - Door opener - Timed Start/Stop"
